### ISSUE TITLE
Error while attempting to build DLL

### ISSUE THREAD

**Issue by bigwhoopgames** [philippj/SteamworksPy#96]
I am getting the following error while using the build_win_64.bat file:

C:\Users\Derp\Downloads\SteamworksPy-master>build_win_64.bat 2022
[*] Building SteamworksPy
[*] Setting up environment
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.5
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.5
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[TEST:dotnet.bat] Checking for ilasm.exe...
[TEST:msbuild.bat] checking for msbuild.exe...
[TEST:winsdk.bat] Checking for 'signtool.exe'...
[TEST:winsdk.bat] Checking for 'ucrt.lib' in LIB...
[TEST:winsdk.bat] Checking for 'kernel32.lib' in LIB...
[TEST:winsdk.bat] Checking for 'corecrt.h' in INCLUDE...
[TEST:winsdk.bat] Checking for 'windows.h' in INCLUDE...
[TEST:cmake.bat] Checking for cmake.exe...
[TEST:cmake.bat] Checking for ninja.exe...
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\VC\Linux\bin\ConnectionManagerExe\ConnectionManager.exe
[TEST:netfxsdk.bat] .NET FX SDK not installed - skipping test.
[TEST:team_explorer.bat] Testing for tf.exe...
[ERROR:team_explorer.bat] 'where tf.exe' failed
[TEST:testwindow.bat] Checking for vstest.console.exe...
[TEST:vcvars.bat] Checking for cl.exe...
[TEST:vcvars.bat] Checking for dumpbin.exe...
[TEST:vcvars.bat] Checking for msvcrt.lib in LIB...
[TEST:vcvars.bat] Checking for vcruntime.h in INCLUDE...
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
[*] SDK available
[*] Building in _build_12558
[*] Copying SteamworksPy.cpp into build root
        1 file(s) copied.
[*] Copying Steamworks redist bins to build root
.\library\sdk\redist\.gitignore
.\library\sdk\redist\steam_api64.dll
.\library\sdk\redist\steam_api64.lib
        3 file(s) copied.
[*] Linking SteamworksSDK into build root
Junction created for .\_build_12558\sdk <<===>> .\library\sdk\
[*] Building SteamworksPy.dll
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

SteamworksPy.cpp
SteamworksPy.cpp(987): error C2660: 'ISteamUser::GetAuthSessionTicket': function does not take 3 arguments
C:\Users\Derp\Downloads\SteamworksPy-master\_build_12558\sdk\steam\isteamuser.h(131): note: see declaration of 'ISteamUser::GetAuthSessionTicket'
SteamworksPy.cpp(987): note: while trying to match the argument list '(char *, int, uint32 *)'
[*] Moving finished library into main repo
The system cannot find the file specified.
[*] Cleanup

C:\Users\Derp\Downloads\SteamworksPy-master>

I have copied the steam SDK files and the steam_api64 files to the correct locations per the readme.

Thank you for taking a look.

**Comment by bigwhoopgames** [comment]
Update:

I was able to compile using the SDK 1.55 version however the example still does not run correctly.
